### PR TITLE
support restore_basebackup_max_target_time

### PR DESCRIPTION
**Pull request by kathia-barahona**
Config parameter for limiting the basebackup selection. This way we can only allow restoring basebackups that were created before any incident.

### CODE REVIEW

**Comment by rikonen** [comment]
It's not quite clear what's the point of having a config option for this vs just not making requests with timestamps you don't want to restore.

**Comment by kathia-barahona** [comment]
> It's not quite clear what's the point of having a config option for this vs just not making requests with timestamps you don't want to restore.

Yes, though the main idea is to allow us a way to avoid any requests that try to restore corrupted backups in case we got incidents. Maybe the naming is not the best. @kmichel-aiven  please correct me if I am wrong

**Comment by rikonen** [comment]
For our internal use cases requests don't go to MyHoard directly so we can / probably should restrict these elsewhere

**Comment by kmichel-aiven** [comment]
> It's not quite clear what's the point of having a config option for this vs just not making requests with timestamps you don't want to restore.

The idea is to restore to the same date as when using `target_time`, but starting from an older basebackup and replaying more binlogs to reach `target_time`. 
This will be slower but helpful if we want to avoid a more recent basebackup, if we suspect something is wrong with the basebackup but not the binlogs.

**Comment by rikonen** [comment]
OK, that can make sense but now the code just raises an error if you give it newer timestamp instead of picking older basebackup to restore. (Also, possibly cleaner approach would be to add some separate operation that can be used to flag a backup as broken and those backups would then automatically be excluded by the existing logic for skipping broken backups.)

**Comment by kathia-barahona** [comment]
> OK, that can make sense but now the code just raises an error if you give it newer timestamp instead of picking older basebackup to restore. (Also, possibly cleaner approach would be to add some separate operation that can be used to flag a backup as broken and those backups would then automatically be excluded by the existing logic for skipping broken backups.)

actually yes, tho that's when we get a restoring request with a specific stream id. I probably missed other cases we perform restores automatically. Need to take a look at this.

**Pull request closed without merging**
