### PR TITLE
remove backup preservation after restoration

### PR DESCRIPTION
**Pull request by kathia-barahona**
# About this change: What it does, why it matters
Remove preservation after the backup is restored. This will help avoiding preserving a backup for too long when it is just locked for restoring

### CODE REVIEW

**Comment by rikonen** [comment]
I'm not sure how we're planning to use this functionality exactly but you could fork N new services from the same old backup and the backup should be preserved until all forks are up, which sounds like it might go against the assumption here that backup is safe to remove once it has been restored.

**Comment by kathia-barahona** [comment]
> I'm not sure how we're planning to use this functionality exactly but you could fork N new services from the same old backup and the backup should be preserved until all forks are up, which sounds like it might go against the assumption here that backup is safe to remove once it has been restored.

Yes, thought about that. More of an experiment here tbh, @rikonen do you think we should keep track of a list service ids that have an ongoing restoration of the backup in the object storage? I considered that, but feels like I am getting into a rabbit hole... 
The main idea is to avoid preserving backups for too long, since currently the master has no way to know when the forks have finished restoring (well, actually yes if we check the standby/fork nodes statuses, but how to know if the backup was meant to be preserved due to restoration?)

**Comment by rikonen** [comment]
I don't think this should be the responsibility of MyHoard at all. In general having new services that start by reusing backups of an existing service modify those backups seems bad, the backups should be considered read-only and not touched. The general management logic should determine when backups need to be retained and when removing those is safe. E.g. the configuration we send to the source service could have a list of new services being forked from that service and the backups used for doing the forking, which the control logic of the source service can then make appropriate request to MyHoard to start preserving a backup when there's an ongoing restoration for it and stop preserving it when last of those goes away.

**Comment by kathia-barahona** [comment]
> I don't think this should be the responsibility of MyHoard at all. In general having new services that start by reusing backups of an existing service modify those backups seems bad, the backups should be considered read-only and not touched. The general management logic should determine when backups need to be retained and when removing those is safe. E.g. the configuration we send to the source service could have a list of new services being forked from that service and the backups used for doing the forking, which the control logic of the source service can then make appropriate request to MyHoard to start preserving a backup when there's an ongoing restoration for it and stop preserving it when last of those goes away.

I agree, then this means we should remove such mechanism from pghoard as well... It has a flag for removing preservation after restoration, tho the fork is the one actually requesting the preservation (master is not aware) before restore. Still dangerous IMHO since the backup can still be removed before the node reaches a setup stage.

Will close this PR and create an issue for changing behavior in pghoard as well.

**Pull request closed without merging**
